
package com.ste.emer.client.SMSManagement;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-03T17:14:26.181+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class ISendMessageWS_SendMessageWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.SMSManagement.stee.com/", "SendMessageWS");

    private ISendMessageWS_SendMessageWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SendMessageWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SendMessageWS ss = new SendMessageWS(wsdlURL, SERVICE_NAME);
        ISendMessageWS port = ss.getSendMessageWSImplPort();  
        
        {
        System.out.println("Invoking sendMessage...");
        com.ste.emer.client.SMSManagement.OutBoundMessage _sendMessage_arg0 = null;
        com.ste.emer.client.SMSManagement.Result _sendMessage__return = port.sendMessage(_sendMessage_arg0);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }

        System.exit(0);
    }

}
