package com.ste.emer.client.SMSManagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-03T17:14:26.300+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://webService.SMSManagement.stee.com/", name = "ISendMessageWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ISendMessageWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://webService.SMSManagement.stee.com/", className = "com.ste.emer.client.SMSManagement.SendMessage")
    @WebMethod
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://webService.SMSManagement.stee.com/", className = "com.ste.emer.client.SMSManagement.SendMessageResponse")
    public com.ste.emer.client.SMSManagement.Result sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ste.emer.client.SMSManagement.OutBoundMessage arg0
    );
}
