package com.ste.emer.client.SMSManagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-12-03T17:14:26.307+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SendMessageWS", 
                  wsdlLocation = "http://192.168.1.96:8082/SMSManagement/SendMessageWS?wsdl",
                  targetNamespace = "http://impl.webService.SMSManagement.stee.com/") 
public class SendMessageWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.SMSManagement.stee.com/", "SendMessageWS");
    public final static QName SendMessageWSImplPort = new QName("http://impl.webService.SMSManagement.stee.com/", "SendMessageWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.96:8082/SMSManagement/SendMessageWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SendMessageWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.96:8082/SMSManagement/SendMessageWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SendMessageWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SendMessageWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessageWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SendMessageWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SendMessageWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SendMessageWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ISendMessageWS
     */
    @WebEndpoint(name = "SendMessageWSImplPort")
    public ISendMessageWS getSendMessageWSImplPort() {
        return super.getPort(SendMessageWSImplPort, ISendMessageWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISendMessageWS
     */
    @WebEndpoint(name = "SendMessageWSImplPort")
    public ISendMessageWS getSendMessageWSImplPort(WebServiceFeature... features) {
        return super.getPort(SendMessageWSImplPort, ISendMessageWS.class, features);
    }

}
